import Head from "next/head";
import axios from "axios";
import { BASE_URL } from "../utils";
import { Content } from "../types";
import ContentCard from "../components/ContentCard";
import NoResults from "../components/NoResults";

interface IProps {
	content: Content[];
}
export default function Home({ content }: IProps) {
	// console.log(content);

	return (
		<>
			<Head>
				<title>Twitter</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/twitter.ico" />
			</Head>
			<div
				className={`grid grid-cols-1 overflow-y-scroll ${
					content.length > 0 && "md:grid-cols-2 3xl:grid-cols-3"
				}  items-center gap-7 px-5 w-full`}
			>
				{content.length > 0 ? (
					content.map((item: Content) => (
						<ContentCard post={item} isShowingOnHome key={item._id} />
					))
				) : (
					<NoResults text={`No Post / Post of selected Category Yet !`} />
				)}
			</div>
		</>
	);
}

export const getServerSideProps = async ({
	query: { topic },
}: {
	query: { topic: string };
}) => {
	let response = await axios.get(`${BASE_URL}/api/post`);

	// console.log(topic + " from index");

	if (topic) {
		response = await axios.get(`${BASE_URL}/api/discover/${topic}`);
	}

	return {
		props: { content: response.data },
	};
};
